CTFd/auth.py
import base64

import requests
from flask import Blueprint
from flask import current_app as app
from flask import redirect, render_template, request, session, url_for
from itsdangerous.exc import BadSignature, BadTimeSignature, SignatureExpired

from CTFd.cache import clear_team_session, clear_user_session
from CTFd.models import Teams, UserFieldEntries, UserFields, Users, db
from CTFd.utils import config, email, get_app_config, get_config
from CTFd.utils import user as current_user
from CTFd.utils import validators
from CTFd.utils.config import is_teams_mode
from CTFd.utils.config.integrations import mlc_registration
from CTFd.utils.config.visibility import registration_visible
from CTFd.utils.crypto import verify_password
from CTFd.utils.decorators import ratelimit
from CTFd.utils.decorators.visibility import check_registration_visibility
from CTFd.utils.helpers import error_for, get_errors, markup
from CTFd.utils.logging import log
from CTFd.utils.modes import TEAMS_MODE
from CTFd.utils.security.auth import login_user, logout_user
from CTFd.utils.security.signing import unserialize
from CTFd.utils.validators import ValidationError

auth = Blueprint("auth", __name__)


@auth.route("/confirm", methods=["POST", "GET"])
@auth.route("/confirm/<data>", methods=["POST", "GET"])
@ratelimit(method="POST", limit=10, interval=60)
def confirm(data=None):
    if not get_config("verify_emails"):
        # If the CTF doesn't care about confirming email addresses then redierct to challenges
        return redirect(url_for("challenges.listing"))

    # User is confirming email account
    if data and request.method == "GET":
        try:
            user_email = unserialize(data, max_age=1800)
        except (BadTimeSignature, SignatureExpired):
            return render_template(
                "confirm.html", errors=["Da ist was schief gegangen, versuche es noch einmal oder melde dich bei info@ehlms-horselock-akademie.de: Your confirmation link has expired"]
            )
        except (BadSignature, TypeError, base64.binascii.Error):
            return render_template(
                "confirm.html", errors=["Da ist was schief gegangen, versuche es noch einmal oder melde dich bei info@ehlms-horselock-akademie.de: Your confirmation token is invalid"]
            )

        user = Users.query.filter_by(email=user_email).first_or_404()
        if user.verified:
            return redirect(url_for("views.settings"))

        user.verified = True
        log(
            "registrations",
            format="[{date}] {ip} - successful confirmation for {name}",
            name=user.name,
        )
        db.session.commit()
        clear_user_session(user_id=user.id)
        email.successful_registration_notification(user.email)
        db.session.close()
        if current_user.authed():
            return redirect(url_for("challenges.listing"))
        return redirect(url_for("auth.login"))

    # User is trying to start or restart the confirmation flow
    if current_user.authed() is False:
        return redirect(url_for("auth.login"))

    user = Users.query.filter_by(id=session["id"]).first_or_404()
    if user.verified:
        return redirect(url_for("views.settings"))

    if data is None:
        if request.method == "POST":
            # User wants to resend their confirmation email
            email.verify_email_address(user.email)
            log(
                "registrations",
                format="[{date}] {ip} - {name} initiated a confirmation email resend",
                name=user.name,
            )
            return render_template(
                "confirm.html", infos=[f"Mail gesendet an: {user.email}!"]
            )
        elif request.method == "GET":
            # User has been directed to the confirm page
            return render_template("confirm.html")


@auth.route("/reset_password", methods=["POST", "GET"])
@auth.route("/reset_password/<data>", methods=["POST", "GET"])
@ratelimit(method="POST", limit=10, interval=60)
def reset_password(data=None):
    if config.can_send_mail() is False:
        return render_template(
            "reset_password.html",
            errors=[
                markup(
                    "This CTF is not configured to send email.<br> Please contact an organizer to have your password reset."
                )
            ],
        )

    if data is not None:
        try:
            email_address = unserialize(data, max_age=1800)
        except (BadTimeSignature, SignatureExpired):
            return render_template(
                "reset_password.html", errors=["Da ist was schief gegangen, versuche es noch einmal oder melde dich bei info@ehlms-horselock-akademie.de: Your reset link has expired"]
            )
        except (BadSignature, TypeError, base64.binascii.Error):
            return render_template(
                "reset_password.html", errors=["Da ist was schief gegangen, versuche es noch einmal oder melde dich bei info@ehlms-horselock-akademie.de: Your reset token is invalid"]
            )

        if request.method == "GET":
            return render_template("reset_password.html", mode="set")
        if request.method == "POST":
            password = request.form.get("password", "").strip()
            user = Users.query.filter_by(email=email_address).first_or_404()
            if user.oauth_id:
                return render_template(
                    "reset_password.html",
                    infos=[
                        "Your account was registered via an authentication provider and does not have an associated password. Please login via your authentication provider."
                    ],
                )

            pass_short = len(password) == 0
            if pass_short:
                return render_template(
                    "reset_password.html", errors=["Bitte wähle ein längeres Passwort"]
                )

            user.password = password
            db.session.commit()
            clear_user_session(user_id=user.id)
            log(
                "logins",
                format="[{date}] {ip} - successful password reset for {name}",
                name=user.name,
            )
            db.session.close()
            email.password_change_alert(user.email)
            return redirect(url_for("auth.login"))

    if request.method == "POST":
        email_address = request.form["email"].strip()
        user = Users.query.filter_by(email=email_address).first()

        get_errors()

        if not user:
            return render_template(
                "reset_password.html",
                infos=[
                    "Du soltest jetzt in deiner Mailbox eine E-Mail mit weiteren Anweisungen finden."
                ],
            )

        if user.oauth_id:
            return render_template(
                "reset_password.html",
                infos=[
                    "The email address associated with this account was registered via an authentication provider and does not have an associated password. Please login via your authentication provider."
                ],
            )

        email.forgot_password(email_address)

        return render_template(
            "reset_password.html",
            infos=[
                "Bitte prüfe deine E-Mailadresse, du solltest Post haben!"
            ],
        )
    return render_template("reset_password.html")


@auth.route("/register", methods=["POST", "GET"])
@check_registration_visibility
@ratelimit(method="POST", limit=10, interval=5)
def register():
    errors = get_errors()
    if current_user.authed():
        return redirect(url_for("challenges.listing"))

    if request.method == "POST":
        name = request.form.get("name", "").strip()
        email_address = request.form.get("email", "").strip().lower()
        password = request.form.get("password", "").strip()

        website = request.form.get("website")
        affiliation = request.form.get("affiliation")
        country = request.form.get("country")

        name_len = len(name) == 0
        names = Users.query.add_columns("name", "id").filter_by(name=name).first()
        emails = (
            Users.query.add_columns("email", "id")
            .filter_by(email=email_address)
            .first()
        )
        pass_short = len(password) == 0
        pass_long = len(password) > 128
        valid_email = validators.validate_email(email_address)
        team_name_email_check = validators.validate_email(name)

        # Process additional user fields
        fields = {}
        for field in UserFields.query.all():
            fields[field.id] = field

        entries = {}
        for field_id, field in fields.items():
            value = request.form.get(f"fields[{field_id}]", "").strip()
            if field.required is True and (value is None or value == ""):
                errors.append("Du musst alle Felder ausfüllen!")
                break

            # Handle special casing of existing profile fields
            if field.name.lower() == "affiliation":
                affiliation = value
                break
            elif field.name.lower() == "website":
                website = value
                break

            if field.field_type == "boolean":
                entries[field_id] = bool(value)
            else:
                entries[field_id] = value

        if country:
            try:
                validators.validate_country_code(country)
                valid_country = True
            except ValidationError:
                valid_country = False
        else:
            valid_country = True

        if website:
            valid_website = validators.validate_url(website)
        else:
            valid_website = True

        if affiliation:
            valid_affiliation = len(affiliation) < 128
        else:
            valid_affiliation = True

        if not valid_email:
            errors.append("Bitte gib eine gültige E-Mailadresse ein!")

CTFd/plugins/challenges/__init__.py
from flask import Blueprint

from CTFd.models import (
    ChallengeFiles,
    Challenges,
    Fails,
    Flags,
    Hints,
    Solves,
    Tags,
    db,
)
from CTFd.plugins import register_plugin_assets_directory
from CTFd.plugins.flags import FlagException, get_flag_class
from CTFd.utils.uploads import delete_file
from CTFd.utils.user import get_ip


class BaseChallenge(object):
    id = None
    name = None
    templates = {}
    scripts = {}
    challenge_model = Challenges

    @classmethod
    def create(cls, request):
        """
        This method is used to process the challenge creation request.

        :param request:
        :return:
        """
        data = request.form or request.get_json()

        challenge = cls.challenge_model(**data)

        db.session.add(challenge)
        db.session.commit()

        return challenge

    @classmethod
    def read(cls, challenge):
        """
        This method is in used to access the data of a challenge in a format processable by the front end.

        :param challenge:
        :return: Challenge object, data dictionary to be returned to the user
        """
        data = {
            "id": challenge.id,
            "name": challenge.name,
            "value": challenge.value,
            "description": challenge.description,
            "category": challenge.category,
            "state": challenge.state,
            "max_attempts": challenge.max_attempts,
            "type": challenge.type,
            "type_data": {
                "id": cls.id,
                "name": cls.name,
                "templates": cls.templates,
                "scripts": cls.scripts,
            },
        }
        return data

    @classmethod
    def update(cls, challenge, request):
        """
        This method is used to update the information associated with a challenge. This should be kept strictly to the
        Challenges table and any child tables.

        :param challenge:
        :param request:
        :return:
        """
        data = request.form or request.get_json()
        for attr, value in data.items():
            setattr(challenge, attr, value)

        db.session.commit()
        return challenge

    @classmethod
    def delete(cls, challenge):
        """
        This method is used to delete the resources used by a challenge.

        :param challenge:
        :return:
        """
        Fails.query.filter_by(challenge_id=challenge.id).delete()
        Solves.query.filter_by(challenge_id=challenge.id).delete()
        Flags.query.filter_by(challenge_id=challenge.id).delete()
        files = ChallengeFiles.query.filter_by(challenge_id=challenge.id).all()
        for f in files:
            delete_file(f.id)
        ChallengeFiles.query.filter_by(challenge_id=challenge.id).delete()
        Tags.query.filter_by(challenge_id=challenge.id).delete()
        Hints.query.filter_by(challenge_id=challenge.id).delete()
        Challenges.query.filter_by(id=challenge.id).delete()
        cls.challenge_model.query.filter_by(id=challenge.id).delete()
        db.session.commit()

    @classmethod
    def attempt(cls, challenge, request):
        """
        This method is used to check whether a given input is right or wrong. It does not make any changes and should
        return a boolean for correctness and a string to be shown to the user. It is also in charge of parsing the
        user's input from the request itself.

        :param challenge: The Challenge object from the database
        :param request: The request the user submitted
        :return: (boolean, string)
        """
        data = request.form or request.get_json()
        submission = data["submission"].strip()
        flags = Flags.query.filter_by(challenge_id=challenge.id).all()
        for flag in flags:
            try:
                if get_flag_class(flag.type).compare(flag, submission):
                    return True, "Richtig!"
            except FlagException as e:
                return False, str(e)
        return False, "Deine Antwort ist falsch oder hat Tippfeler drinnen. Bitte schau nochmal ganz genau auf die Schreibweise oder überprüfe die Antwort :)"

    @classmethod
    def solve(cls, user, team, challenge, request):
        """
        This method is used to insert Solves into the database in order to mark a challenge as solved.

        :param team: The Team object from the database
        :param chal: The Challenge object from the database
        :param request: The request the user submitted
        :return:
        """
        data = request.form or request.get_json()
        submission = data["submission"].strip()
        solve = Solves(
            user_id=user.id,
            team_id=team.id if team else None,
            challenge_id=challenge.id,
            ip=get_ip(req=request),
            provided=submission,
        )
        db.session.add(solve)
        db.session.commit()

    @classmethod
    def fail(cls, user, team, challenge, request):
        """
        This method is used to insert Fails into the database in order to mark an answer incorrect.

        :param team: The Team object from the database
        :param chal: The Challenge object from the database
        :param request: The request the user submitted
        :return:
        """
        data = request.form or request.get_json()
        submission = data["submission"].strip()
        wrong = Fails(
            user_id=user.id,
            team_id=team.id if team else None,
            challenge_id=challenge.id,
            ip=get_ip(request),
            provided=submission,
        )
        db.session.add(wrong)
        db.session.commit()


class CTFdStandardChallenge(BaseChallenge):
    id = "standard"  # Unique identifier used to register challenges
    name = "standard"  # Name of a challenge type
    templates = {  # Templates used for each aspect of challenge editing & viewing
        "create": "/plugins/challenges/assets/create.html",
        "update": "/plugins/challenges/assets/update.html",
        "view": "/plugins/challenges/assets/view.html",
    }
    scripts = {  # Scripts that are loaded when a template is loaded
        "create": "/plugins/challenges/assets/create.js",
        "update": "/plugins/challenges/assets/update.js",
        "view": "/plugins/challenges/assets/view.js",
    }
    # Route at which files are accessible. This must be registered using register_plugin_assets_directory()
    route = "/plugins/challenges/assets/"
    # Blueprint used to access the static_folder directory.
    blueprint = Blueprint(
        "standard", __name__, template_folder="templates", static_folder="assets"
    )
    challenge_model = Challenges


def get_chal_class(class_id):
    """
    Utility function used to get the corresponding class from a class ID.

    :param class_id: String representing the class ID
    :return: Challenge class
    """
    cls = CHALLENGE_CLASSES.get(class_id)
    if cls is None:
        raise KeyError
    return cls


"""
Global dictionary used to hold all the Challenge Type classes used by CTFd. Insert into this dictionary to register
your Challenge Type.
"""
CHALLENGE_CLASSES = {"standard": CTFdStandardChallenge}


def load(app):
    register_plugin_assets_directory(app, base_path="/plugins/challenges/assets/")

CTFd/themes/de/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{{ Configs.ctf_name }}</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" href="{{ Configs.ctf_small_icon }}" type="image/x-icon">
	<link rel="stylesheet" href="{{ url_for('views.themes', path='css/fonts.css') }}">
	<link rel="stylesheet" href="{{ url_for('views.themes', path='css/main.css') }}">
	<link rel="stylesheet" href="{{ url_for('views.themes', path='css/core.css') }}">
	{% block stylesheets %}
	{% endblock %}

	{{ Plugins.styles }}
	<script type="text/javascript">
		var init = {
			'urlRoot': "{{ request.script_root }}",
			'csrfNonce': "{{ Session.nonce }}",
			'userMode': "{{ Configs.user_mode }}",
			'userId': {{ Session.id }},
			'start': {{ Configs.start | tojson }},
			'end': {{ Configs.end | tojson }},
			'theme_settings': {{ Configs.theme_settings | tojson }}
		}
	</script>
	{{ Configs.theme_header }}
</head>
<body>
	{% include "components/navbar.html" %}

	<main role="main">
		{% block content %}
		{% endblock %}
	</main>

	<footer class="footer" style="z-index:0">
		<div class="container text-center">
			<a href="/info/impressum" class="text-secondary">
				<small class="text-muted">Impressum</small>
			</a>
		</div>
	</footer>

	<script defer src="{{ url_for('views.themes', path='js/vendor.bundle.js') }}"></script>
	<script defer src="{{ url_for('views.themes', path='js/core.js') }}"></script>
	<script defer src="{{ url_for('views.themes', path='js/helpers.js') }}"></script>

	{% block entrypoint %}
	<script defer src="{{ url_for('views.themes', path='js/pages/main.js') }}"></script>
	{% endblock %}

	{% block scripts %}
	{% endblock %}

	{{ Plugins.scripts }}

	{{ Configs.theme_footer }}
</body>
</html>

CTFd/themes/de/templates/challenge.html
<div class="modal-dialog" role="document">
	<div class="modal-content">
		<div class="modal-body">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
			<ul class="nav nav-tabs">
				<li class="nav-item">
					<a class="nav-link active" href="#challenge">Aufgabe</a>
				</li>
				{% block solves %}
					<li class="nav-item">
						<a class="nav-link challenge-solves" href="#solves">
							{% if solves != None %}
								{{ solves }} {% if solves == 1 %}anderer Detektiv{% else %}andere Detektive{% endif %}
							{% endif %}
						</a>
					</li>
				{% endblock %}
			</ul>
			<div role="tabpanel">
				<div class="tab-content">
					<div role="tabpanel" class="tab-pane fade show active" id="challenge">
						<h2 class='challenge-name text-center pt-3'>
							{{ challenge.name }}
						</h2>
						<h3 class="challenge-value text-center">
							{{ challenge.value }}
						</h3>

						<div class="challenge-tags text-center">
							{% block tags %}
								{% for tag in tags %}
									<span class='badge badge-info challenge-tag'>{{ tag }}</span>
								{% endfor %}
							{% endblock %}
						</div>

						<span class="challenge-desc">{% block description %}{{ challenge.html }}{% endblock %}</span>

						<div class="challenge-hints hint-row row">
							{% for hint in hints %}
								<div class='col-md-12 hint-button-wrapper text-center mb-3'>
									<a class="btn btn-info btn-hint btn-block load-hint" href="javascript:;" data-hint-id="{{ hint.id }}">
										{% if hint.content %}
											<small>
												Hinweis anschauen
											</small>
										{% else %}
											{% if hint.cost %}
												<small>
													Hinweis für {{ hint.cost }} Punkte anschauen
												</small>
											{% else %}
												<small>
													Hinweis anschauen
												</small>
											{% endif %}
										{% endif %}
									</a>
								</div>
							{% endfor %}
						</div>

						<div class="row challenge-files text-center pb-3">
							{% for file in files %}
								<div class='col-md-4 col-sm-4 col-xs-12 file-button-wrapper d-block'>
									<a class='btn btn-info btn-file mb-1 d-inline-block px-2 w-100 text-truncate'
									   href='{{ file }}'>
										<i class="fas fa-download"></i>
										<small>
											{% set segments = file.split('/') %}
											{% set file = segments | last %}
											{% set token = file.split('?') | last %}
											{% if token %}
												{{ file | replace("?" + token, "") }}
											{% else %}
												{{ file }}
											{% endif %}
										</small>
									</a>
								</div>
							{% endfor %}
						</div>

						{% if max_attempts > 0 %}
						<div class="row text-center">
							<div class="col-md-12">
								<p>
									{{ attempts }}/{{ max_attempts }} Versuche
								</p>
							</div>
						</div>
						{% endif %}

						<div class="row submit-row">
							<div class="col-md-9 form-group">
								{% block input %}
									<input id="challenge-id" class="challenge-id" type="hidden" value="{{ challenge.id }}">
									<input id="challenge-input" class="challenge-input" type="text" name="answer" placeholder="Lösung"/>
								{% endblock %}
							</div>
							<div class="col-md-3 form-group key-submit">
								{% block submit %}
								<button id="challenge-submit" class="challenge-submit" type="submit">
									Beweis abgeben
								</button>
								{% endblock %}
							</div>
						</div>

						<div class="row notification-row">
							<div class="col-md-12">
								<div id="result-notification" class="alert alert-dismissable text-center w-100"
									 role="alert" style="display: none;">
									<strong id="result-message"></strong>
								</div>
							</div>
						</div>
					</div>

					<div role="tabpanel" class="tab-pane fade" id="solves">
						<div class="row">
							<div class="col-md-12">
								<table class="table table-striped text-center">
									<thead>
									<tr>
										<td><b>Name</b>
										</td>
										<td><b>Date</b>
										</td>
									</tr>
									</thead>
									<tbody id="challenge-solves-names">
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

CTFd/themes/de/templates/challenges.html
{% extends "base.html" %}

{% block stylesheets %}
	<link rel="stylesheet" href="{{ url_for('views.themes', path='css/challenge-board.css') }}">
{% endblock %}

{% block content %}
<div class="jumbotron">
	<div class="container">
		<h1>Detektiv-Training</h1>
	</div>
</div>

<div class="modal fade" id="challenge-window" tabindex="-1" role="dialog">
</div>

<div class="container">
	<div class="row">
		<div class="col-md-12">
			{% include "components/errors.html" %}
		</div>
	</div>

	<div id='challenges-board'>
		<div class="min-vh-50 d-flex align-items-center">
			<div class="text-center w-100">
				<i class="fas fa-circle-notch fa-spin fa-3x fa-fw spinner"></i>
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block scripts %}
{% endblock %}

{% block entrypoint %}
	<script defer src="{{ url_for('views.themes', path='js/pages/challenges.js') }}"></script>
{% endblock %}

CTFd/themes/de/templates/config.html
<form>
  <div class="form-group">
    <label>Challenge Window Size</label>
    <select class="form-control custom-select" name="challenge_window_size">
        <option value="sm">Small</option>
        <option value="norm">Normal</option>
        <option value="lg">Large</option>
        <option value="xl">Extra Large</option>
    </select>
  </div>
  <button type="submit" class="btn btn-primary float-right">Update</button>
</form>

CTFd/themes/de/templates/confirm.html
{% extends "base.html" %}

{% block stylesheets %}
{% endblock %}

{% block content %}
	<div class="jumbotron">
		<div class="container">
			<h1>Bestätige deine E-Mail</h1>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-md-6 offset-md-3">
				{% include "components/errors.html" %}

				<h5 class="text-center">
					Du solltest nun unter der angegebenen E-Mail eine Nachricht von uns erhalten haben.
				</h5>

				<br>

				<h5 class="text-center">
					Bitte klicke den Link in der Nachricht zur Bestätigung deiner Einschreibung.
				</h5>

				<br>

				<h5 class="text-center">
					Wenn du die E-Mail nicht finden kannst, überprüfe bitte deinen <i>Spam</i>-Ordner oder kontaktiere unser Sekretariat unter info@ehlms-horselock-akademie.de.
				</h5>

				<hr>

				{% with form = Forms.auth.ConfirmForm() %}
				<form method="POST" action="{{ url_for('auth.confirm') }}">
					<div class="row">
						<div class="col-md-6">
							{{ form.submit(class="btn btn-md btn-primary btn-outlined w-100") }}
						</div>
						<div class="col-md-6">
							<a href="{{ url_for('views.settings') }}" class="btn btn-md btn-secondary btn-outlined w-100">
								E-Mail Adresse ändern
							</a>
						</div>
						{{ form.nonce() }}
					</div>
				</form>
				{% endwith %}
			</div>
		</div>
	</div>
{% endblock %}

{% block scripts %}
{% endblock %}

CTFd/themes/de/templates/login.html
{% extends "base.html" %}

{% block stylesheets %}
{% endblock %}

{% block content %}
<div class="jumbotron">
	<div class="container">
		<h1>Login</h1>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-6 offset-md-3">
			{% include "components/errors.html" %}

			<p>
				Hallo Jung-Detektiv!
			</p>
			<p>
				Hier kannst du dich mit deinem vorher gewählten Benutzernamen und Passwort einwählen. Wenn du dich noch nicht angemeldet hast, dann klick bitte oben rechts auf "Zur Einschreibung".
			</p>
			<p>
				Wenn du alles richtig eingegeben hast, kannst du beispielsweise die Steckbriefe deiner Magister anschauen oder an den Detektivübungen teilnehmen!
			</p>
			<p>
				Solltest du irgendwelche Fragen haben, schreibe bitte unserem Sekretariat eine Mail unter: info@ehlms-horselock-akademie.de.
			</p>

			{% if integrations.mlc() %}
			<a class="btn btn-secondary btn-lg btn-block" href="{{ url_for('auth.oauth_login') }}">
				Login with Major League Cyber
			</a>

			<hr>
			{% endif %}

			{% with form = Forms.auth.LoginForm() %}
			<form method="post" accept-charset="utf-8" autocomplete="off">
				<div class="form-group">
					<b>{{ form.name.label }}</b>
					{{ form.name(class="form-control", value=name) }}
				</div>
				<div class="form-group">
					<b>{{ form.password.label }}</b>
					{{ form.password(class="form-control", value=password) }}
				</div>
				<div class="row pt-3">
					<div class="col-md-6">
						<a class="float-left align-text-to-button text-secondary" href="{{ url_for('auth.reset_password') }}">
							Codewort vergessen?
						</a>
					</div>
					<div class="col-md-6">
						{{ form.submit(class="btn btn-md btn-primary btn-outlined float-right") }}
					</div>
				</div>
				{{ form.nonce() }}
			</form>
			{% endwith %}
		</div>
	</div>
</div>
{% endblock %}

{% block scripts %}
{% endblock %}

CTFd/themes/de/templates/notifications.html
{% extends "base.html" %}

{% block content %}
	<div class="jumbotron">
		<div class="container">
			<h1>Postfach</h1>
		</div>
	</div>
	<div class="container">
		{% if not notifications %}
		<h2 class="text-center">Keine Nachrichten bisher! Schau später noch mal vorbei.</h2>
		{% endif %}
		{% for notification in notifications %}
		<div class="card bg-light mb-4">
			<div class="card-body">
				<h3 class="card-title">{{ notification.title }}</h3>
				<blockquote class="blockquote mb-0">
					<p>{{ notification.html }}</p>
					<small class="text-muted"><span data-time="{{ notification.date | isoformat }}"></span></small>
				</blockquote>
			</div>
		</div>
		{% endfor %}
	</div>
{% endblock %}

{% block entrypoint %}
	<script defer src="{{ url_for('views.themes', path='js/pages/notifications.js') }}"></script>
{% endblock %}

CTFd/themes/de/templates/page.html
{% extends "base.html" %}

{% block content %}
	<div class="container">
	{{ content | safe }}
	</div>
{% endblock %}

CTFd/themes/de/templates/register.html
{% extends "base.html" %}

{% block stylesheets %}
{% endblock %}

{% block content %}
<div class="jumbotron">
	<div class="container">
		<h1>Einschreibung</h1>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-6 offset-md-3">
			{% include "components/errors.html" %}

			{% if integrations.mlc() %}
			<a class="btn btn-secondary btn-lg btn-block" href="{{ url_for('auth.oauth_login') }}">
				Login with Major League Cyber
			</a>

			<hr>
			{% endif %}

			{% with form = Forms.auth.RegistrationForm() %}
			{% from "macros/forms.html" import render_extra_fields %}
			<form method="post" accept-charset="utf-8" autocomplete="off" role="form">
				<div class="form-group">
					<b>{{ form.name.label }}</b>
					{{ form.name(class="form-control", value=name) }}
					<small class="form-text text-muted">
						Schreibe hier bitte deinen Wunschnamen herein. Irgend ein Phantasiename. Unter welchem Detektivnamen möchtest du bekannt werden?
					</small>
				</div>
				<div class="form-group">
					<b>{{ form.email.label }}</b>
					{{ form.email(class="form-control", value=email) }}
					<small class="form-text text-muted">
						Unser System braucht eine Mailadresse um dir z.B. einen Passwortreset zu ermöglichen. (Eine E-Mailadresse kann nicht für zwei Accounts verwendet werden.)
					</small>
				</div>
				<div class="form-group">
					<b>{{ form.password.label }}</b>
					{{ form.password(class="form-control", value=password) }}
					<small class="form-text text-muted">
					Dein Codewort ist dein eigenes geheimes Passwort, was du dir gut merken musst und keinem weitergeben darfst. Hiermit kannst du deinen Zugang zum Akademiesystem schützen.
					</small>
				</div>
				{{ form.nonce() }}

				{{ render_extra_fields(form.extra) }}

				<div class="row pt-3">
					<div class="col-md-12">
						{{ form.submit(class="btn btn-md btn-primary btn-outlined float-right") }}
					</div>
				</div>

				{% if Configs.tos_or_privacy %}
				<div class="row pt-3">
					<div class="col-md-12 text-center">
						<small class="text-muted text-center">
							By registering, you agree to the
							<a href="{{ Configs.privacy_link }}" rel="noopener" target="_blank">privacy policy</a>
							and <a href="{{ Configs.tos_link }}" rel="noopener" target="_blank">terms of service</a>
						</small>
					</div>
				</div>
				{% endif %}
			</form>
			{% endwith %}
		</div>
	</div>
</div>
{% endblock %}

{% block scripts %}
{% endblock %}